---
title: "Workshop 4.9 Solution"
author: "Veerasak Kritsanapraphan"
date: "2/1/2020"
output:
  word_document: default
  html_document: default
---

```{r message=FALSE, warning=FALSE}
library(class)
library(caret)
library(e1071)
library(adabag)
library(gbm)
library(fastDummies)
library(randomForest)
library(dplyr)
telco <- read.csv("WA_Fn-UseC_-Telco-Customer-Churn.csv", header=TRUE)
```

### Remove NA
```{r}
str(telco)
telco <- na.omit(telco)
```

### Data Sampling
```{r}
set.seed(123)
index <- sample(2, nrow(telco), replace=TRUE, prob=c(0.7,0.3) )
traindata <- telco[index==1,]
testdata <- telco[index==2,]
sprintf("Number of Record in Training Dataset is %d" , nrow(traindata))
sprintf("Number of Record in Testing Dataset is %d" , nrow(testdata))
```

### Train Random Forest Model  
```{r}  
Formula <- Churn ~ gender + SeniorCitizen + Partner + tenure + PhoneService + MultipleLines + OnlineBackup + Contract + PaperlessBilling + PaymentMethod + MonthlyCharges + TotalCharges

rf_model <- randomForest(Formula, data=traindata, nTree=500)  
plot(rf_model)
```  


### Evaluate Testing Model  
```{r}
prediction <- predict(rf_model, testdata)
confusionMatrix(prediction, testdata$Churn)  
```  

### Importance Valiables
```{r}
#getTree(rf_model, 1, labelVar=TRUE)
importance(rf_model)
```


## Train Boosting Model
```{r}
churn.adaboost <- boosting(Formula, data=traindata, boost=TRUE, mfinal=10)

```



### Predict 
```{r}
table(churn.adaboost$class, traindata$Churn)
prediction <- predict(churn.adaboost, newdata=testdata)
table(prediction$class, testdata$Churn)
confusionMatrix(as.factor(prediction$class), testdata$Churn)
```

### Variable Importance
```{r}
importanceplot(churn.adaboost, horiz=TRUE, cex.names=.6)
```


